version: '3.8'

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "443:3000"
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/certs:/etc/grafana/certs
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SERVER_PROTOCOL=https
      - GF_SERVER_CERT_FILE=/etc/grafana/certs/cert.crt
      - GF_SERVER_CERT_KEY=/etc/grafana/certs/key.key
    depends_on:
      - loki
      - prometheus

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "8443:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/web-config.yml:/etc/prometheus/web-config.yml
      - ./prometheus/certs:/etc/prometheus/certs
    command:
      - '--web.config.file=/etc/prometheus/web-config.yml'
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - loki


  loki:
    image: grafana/loki
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml


  promtail:
    image: grafana/promtail
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /run/promtail:/run/promtail
      - ./promtail/promtail-config.yaml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80" 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - grafana

volumes:
  grafana_data:
